[package]
name = "install-cert"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls-pemfile = "0.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.32", features = ["Win32_Security_Cryptography", "Win32_Foundation"] }
